# Generated by Django 4.1 on 2022-08-31 22:00

import django.contrib.postgres.fields
import django.core.validators
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="newsletter name")),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        default="THURSDAY",
                        max_length=50,
                        verbose_name="send newsletter on set weekday",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="subscribed email")),
                ("slug", models.SlugField(max_length=250)),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=80),
                        size=None,
                        verbose_name="newsletter keywords",
                    ),
                ),
                (
                    "domains",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=80),
                        size=None,
                        verbose_name="newsletter domains",
                    ),
                ),
                (
                    "score_threshold",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[django.core.validators.MaxValueValidator(1000)],
                        verbose_name="filter out stories below set score threshold",
                    ),
                ),
                (
                    "stories_per_keyword_max_count",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(3),
                        ],
                        verbose_name="max number of stories per keyword",
                    ),
                ),
                ("verified", models.BooleanField(default=False, verbose_name="is email verified")),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
