# Generated by Django 4.0.1 on 2022-05-15 21:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="domens",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=80),
                size=None,
                verbose_name="newsletter domens",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="email",
            field=models.EmailField(
                max_length=254, verbose_name="email subscribed to this newsletter"
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="max_threads_count",
            field=models.PositiveSmallIntegerField(
                choices=[("3", "Three"), ("5", "Five"), ("10", "Ten")],
                default="5",
                help_text="max number of threads per single tag",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="name",
            field=models.CharField(max_length=200, verbose_name="newsletter name"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=80),
                size=None,
                verbose_name="newsletter tags",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="email verified"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="weekday",
            field=models.CharField(
                choices=[
                    ("MONDAY", "Monday"),
                    ("TUESDAY", "Tuesday"),
                    ("WEDNESDAY", "Wednesday"),
                    ("THURSDAY", "Thursday"),
                    ("FRIDAY", "Friday"),
                    ("SATURDAY", "Saturday"),
                    ("SUNDAY", "Sunday"),
                ],
                default="THURSDAY",
                help_text="the weekday on which the newsletter will be sent",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="comments_count",
            field=models.IntegerField(null=True, verbose_name="thread comments count"),
        ),
        migrations.AlterField(
            model_name="thread",
            name="comments_link",
            field=models.URLField(
                max_length=250, null=True, verbose_name="link to thread comments"
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="link",
            field=models.URLField(max_length=700, verbose_name="story link"),
        ),
        migrations.AlterField(
            model_name="thread",
            name="score",
            field=models.IntegerField(null=True, verbose_name="thread score"),
        ),
        migrations.AlterField(
            model_name="thread",
            name="title",
            field=models.CharField(max_length=100, verbose_name="thread title"),
        ),
    ]
