# Generated by Django 4.0.4 on 2022-05-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_alter_newsletter_domens_alter_newsletter_email_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Thread",
        ),
    ]
