# Generated by Django 4.0.4 on 2022-08-21 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_delete_thread"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramNewsletter",
            fields=[
                (
                    "newsletter_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="newsletter.newsletter",
                    ),
                ),
                ("user_id", models.PositiveIntegerField(verbose_name="telegram user id")),
            ],
            options={
                "ordering": ["-created"],
            },
            bases=("newsletter.newsletter",),
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="email",
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="verified",
        ),
        migrations.CreateModel(
            name="EmailNewsletter",
            fields=[
                (
                    "newsletter_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="newsletter.newsletter",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="email subscribed to this newsletter"
                    ),
                ),
                ("verified", models.BooleanField(default=False, verbose_name="email verified")),
                ("slug", models.SlugField(max_length=250)),
            ],
            options={
                "ordering": ["-created"],
            },
            bases=("newsletter.newsletter",),
        ),
    ]
