# Generated by Django 4.0.4 on 2022-05-15 21:34

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "thread_id",
                    models.PositiveBigIntegerField(help_text="hackernews thread id", unique=True),
                ),
                ("link", models.URLField(max_length=700, verbose_name="story link")),
                ("title", models.CharField(max_length=100, verbose_name="thread title")),
                ("score", models.IntegerField(null=True, verbose_name="thread score")),
                (
                    "comments_count",
                    models.IntegerField(null=True, verbose_name="thread comments count"),
                ),
                (
                    "comments_link",
                    models.URLField(
                        max_length=250, null=True, verbose_name="link to thread comments"
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
    ]
