# Generated by Django 4.0.4 on 2022-05-21 21:46

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="thread_created_at",
            field=models.DateTimeField(
                default=str(timezone.now()), verbose_name="parsed thread date of creation"
            ),
            preserve_default=False,
        ),
    ]
