# Generated by Django 4.1 on 2022-12-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0003_alter_thread_thread_id_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="link",
            field=models.URLField(max_length=2000, verbose_name="story link"),
        ),
    ]
