# Generated by Django 4.1 on 2022-12-12 20:47

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0005_trigram_extension"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thread",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(db_index=True, verbose_name="comment's text body"),
        ),
        migrations.AlterField(
            model_name="thread",
            name="title",
            field=models.CharField(db_index=True, max_length=100, verbose_name="thread title"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                django.db.models.functions.text.Upper("body"), name="body_upper_index"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["body"], name="body_gin_index", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("body"), name="gin_trgm_ops"
                ),
                name="body_upper_gin_index",
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                django.db.models.functions.text.Upper("title"), name="title_upper_index"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="title_gin_index", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("title"), name="gin_trgm_ops"
                ),
                name="title_upper_gin_index",
            ),
        ),
    ]
