# Generated by Django 4.1.4 on 2023-02-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0006_alter_thread_options_alter_thread_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.CharField(max_length=10000, verbose_name="comment's text body"),
        ),
    ]
