# Generated by Django 4.1.4 on 2023-02-21 20:15

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0007_alter_comment_body"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["body"], name="scraper_com_body_ecb520_hash"
            ),
        ),
    ]
