# Generated by Django 4.1.4 on 2023-02-21 20:01

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0007_alter_comment_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.CharField(
                db_index=True, max_length=10000, verbose_name="comment's text body"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                django.db.models.functions.text.Upper("body"), name="body_upper_index"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["body"], name="body_gin_index", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("body"), name="gin_trgm_ops"
                ),
                name="body_upper_gin_index",
            ),
        ),
    ]
