# Generated by Django 4.1.4 on 2023-02-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0008_comment_scraper_com_body_ecb520_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.CharField(max_length=20000, verbose_name="comment's text body"),
        ),
    ]
