# Generated by Django 4.1.4 on 2023-03-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0009_alter_comment_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_comments",
                to="scraper.comment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_id",
            field=models.PositiveIntegerField(db_index=True, verbose_name="comment id"),
        ),
    ]
