# Generated by Django 4.1 on 2022-08-31 22:16

import django.contrib.postgres.fields
import django.core.validators
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("chat_id", models.PositiveIntegerField(verbose_name="telegram chat id")),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=80),
                        size=None,
                        verbose_name="feed keywords",
                    ),
                ),
                (
                    "score_threshold",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[django.core.validators.MaxValueValidator(1000)],
                        verbose_name="Threshold to pass for a story to be sent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
