# Generated by Django 4.1 on 2022-12-03 01:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0004_alter_thread_link"),
        ("telegram_feed", "0005_alter_userfeed_score_threshold"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfeed",
            old_name="keywords",
            new_name="old_keywords",
        ),
        migrations.AddField(
            model_name="userfeed",
            name="comments",
            field=models.ManyToManyField(related_name="user_feeds", to="scraper.comment"),
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="keyword itself",
                    ),
                ),
                (
                    "is_full_match",
                    models.BooleanField(default=False, verbose_name="search a whole word match"),
                ),
                (
                    "search_threads",
                    models.BooleanField(default=True, verbose_name="search in thread's title field"),
                ),
                (
                    "search_comments",
                    models.BooleanField(default=True, verbose_name="search in comment's body field"),
                ),
                (
                    "user_feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="telegram_feed.userfeed",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
