# Generated by Django 4.1 on 2022-12-06 23:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_feed", "0006_rename_keywords_userfeed_old_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeed",
            name="old_keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=80),
                default=list,
                size=None,
                verbose_name="feed keywords",
            ),
        ),
    ]
