# Generated by Django 4.1.4 on 2023-02-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0008_comment_scraper_com_body_ecb520_hash"),
        ("telegram_feed", "0008_migrate_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeed",
            name="subscriptions",
            field=models.ManyToManyField(related_name="subscription_user_feeds", to="scraper.thread"),
        ),
    ]
