# Generated by Django 4.1.4 on 2023-03-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_feed", "0012_userfeed_hn_username_userfeed_reply_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramupdate",
            name="update_id",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="userfeed",
            name="chat_id",
            field=models.PositiveBigIntegerField(verbose_name="telegram chat id"),
        ),
    ]
