# Generated by Django 4.1.4 on 2023-03-14 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_feed", "0013_alter_telegramupdate_update_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="keyword",
            options={},
        ),
        migrations.AlterModelOptions(
            name="telegramupdate",
            options={},
        ),
        migrations.AlterModelOptions(
            name="userfeed",
            options={},
        ),
    ]
