# Generated by Django 4.1.7 on 2024-02-06 00:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_feed', '0014_alter_keyword_options_alter_telegramupdate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='hn_username',
            field=models.CharField(max_length=15, null=True, verbose_name='hacker news username'),
        ),
        migrations.CreateModel(
            name='FollowedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('username', models.CharField(max_length=15, verbose_name='hacker news username')),
                ('follow_threads', models.BooleanField(default=True, verbose_name="follow user's threads")),
                ('follow_comments', models.BooleanField(default=True, verbose_name="follow user's comments")),
                ('user_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_list', to='telegram_feed.userfeed')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
